name = "radar-ofertas-telegram"
main = "src/index.ts"
compatibility_date = "2026-09-17"

[triggers]
crons = ["17 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "radar-ofertas-db"
database_id = "a1ec2887-3027-420e-ac8f-90d11d5be064"
migrations_dir = "migrations"

[vars]
GPT_ANALYSIS_ENABLED = "false"
AI_MONTHLY_BUDGET_USD = "2"
